name: 'Veracode Upload And Scan'
description: 'Upload files to veracode and start a static scan.'
inputs:
  appname:  # id of input
    description: 'appname'
    required: true
    default: '${{ github.repository }}'
  createprofile:  # id of input
    description: 'createprofile'
    required: true
    default: true
  filepath:  # id of input
    description: 'filepath'
    required: true
  version:  # id of input
    description: 'version'
    required: true
    default: 'Scan from Github job: ${{ github.run_id }}'
  vid:  # id of input
    description: 'vid'
    required: true
  vkey:  # id of input
    description: 'vkey'
    required: true
  createsandbox: 
    description: 'true or flase'
    required: false
  sandboxname:
    description: 'name of the sandbox'
    required: false
  scantimeout:
    description: 'wait X minutes for the scan to complete'
    required: false
  exclude:
    description: 'modules to exclude from module selection'
    required: false
  include:
    description: 'modules to include in module selection'
    required: false
  criticality:
    description: 'business criticality - policy selection'
    required: false
  pattern:
    description: 'filename pattern'
    required: false
  replacement:
    description: 'replacement'
    required: false
  sandboxid:
    description: 'specify to scan in a sandbox'
    required: false
  scanallnonfataltoplevelmodules:
    description: 'All top level modules'
    required: false
  selected:
    description: 'platform selected modules'
    required: false
  selectedpreviously:
    description: 'selected modules like from previous scan'
    required: false
  teams:
    description: 'teams'
    required: false
  toplevel:
    description: 'teams'
    required: false
  deleteincompletescan:
    description: 'automatically delete the current scan if there are any errors when uploading files or starting the scan'
    required: false
  
    
 
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.appname }}
    - ${{ inputs.createprofile }}
    - ${{ inputs.filepath }}
    - ${{ inputs.version }}
    - ${{ inputs.vid }}
    - ${{ inputs.vkey }}
    - ${{ inputs.createsandbox}}
    - ${{ inputs.sandboxname }}
    - ${{ inputs.scantimeout }}
    - ${{ inputs.exclude }}
    - ${{ inputs.include }}
    - ${{ inputs.criticality }}
    - ${{ inputs.pattern }}
    - ${{ inputs.replacement }}
    - ${{ inputs.sandboxid }}
    - ${{ inputs.scanallnonfataltoplevelmodules }}
    - ${{ inputs.selected }}
    - ${{ inputs.selectedpreviously }}
    - ${{ inputs.teams }}
    - ${{ inputs.toplevel }}
    - ${{ inputs.deleteincompletescan }}
